
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/rust-cross/manylinux_2_28-cross:aarch64"
pre-build = ["apt install libclang-dev -y"]

[target.arm-unknown-linux-gnueabi]
image = "ghcr.io/rust-cross/manylinux_2_28-cross:armv7"
pre-build = ["apt install libclang-dev -y"]

[target.x86_64-unknown-linux-gnu]
image = "quay.io/pypa/manylinux_2_28_x86_64:latest"
pre-build = ["cat /etc/os-release && yum install clang -y"]
